### ISSUE TITLE
Error while running npm run build_prod cmd

### ISSUE THREAD

**Issue by gajusp** [mgechev/angular2-ngc-rollup-build#12]
Hi,

I m getting below error, 
npm run build_prod

> angular2-min@1.0.0 build_prod C:\Users\\Downloads\angular2-ngc-rollup-build-master
> npm run clean && npm run ngc && npm run build && npm run rollup && npm run es5 && npm run minify

> angular2-min@1.0.0 clean C:\Users\\Downloads\angular2-ngc-rollup-build-master
> rm -rf dist && rm -rf app/*.ngfactory.ts && cd compiled && find . ! -name 'main-prod.ts' -type f -exec rm -f {} + && cd ..

> angular2-min@1.0.0 ngc C:\Users\\Downloads\angular2-ngc-rollup-build-master
> ngc -p tsconfig.json && cp app/* compiled

Error at C:/Users//Downloads/angular2-ngc-rollup-build-master/node_modules/rxjs/Subject.d.ts:16:22: Class 'Subject<T>' incorrectly extends base class 'Observable<T>'.
  Types of property 'lift' are incompatible.
    Type '<T, R>(operator: Operator<T, R>) => Observable<T>' is not assignable to type '<R>(operator: Operator<T, R>) => Observable<R>'.
      Type 'Observable<T>' is not assignable to type 'Observable<R>'.
        Type 'T' is not assignable to type 'R'.

Please help me to configure the roll up 

Thanks in advance

**Comment by mgechev** [comment]
That was problem in rxjs after fixes in the typescript's type checker. You can look online for details.

**Comment by mgechev** [comment]
BTW, also this is a demo. I don't recommend you using it. Try angular-cli or Angular seed.
