### ISSUE TITLE
npm run es5 fails

### ISSUE THREAD

**Issue by detectedstealth** [mgechev/angular2-ngc-rollup-build#2]
Following through the blog post the script build_prod failed and I was able to narrow it down to the es5 script.

Now when running the es5 command in the terminal using typescript 1.8 it works as expected without any issues. However when running using the typescript 1.9.0.dev version used in this project it fails with the following:

```
$ ./node_modules/typescript/bin/tsc --target es5 --allowJs dist/bundle.es2015.js --out dist/bundle.js
dist/bundle.es2015.js(5101,15): error TS2300: Duplicate identifier '_subscribe'.
dist/bundle.es2015.js(5186,7): error TS2300: Duplicate identifier '_subscribe'.
```

Looks like this is a rollup.js issue, where when compiling to the bundle.es2015.js file it left duplicate identifiers? Or is it a bigger issue?

I tried reverting the typescript version used down to 1.8 however it seems that ngc is dependent on version 1.9.0-dev

```
> angular2-min@1.0.0 ngc angular2-ngc-rollup-build-master
> ngc -p . && cp app/* compiled

Error: Metadata emit requires the sourceFiles are passed to WriteFileCallback. Update to TypeScript ^1.9.0-dev
```

**Comment by mgechev** [comment]
```
$ ./node_modules/typescript/bin/tsc --target es5 --allowJs dist/bundle.es2015.js --out dist/bundle.js
dist/bundle.es2015.js(5101,15): error TS2300: Duplicate identifier '_subscribe'.
dist/bundle.es2015.js(5186,7): error TS2300: Duplicate identifier '_subscribe'.
```

It is mentioned in the blog post. This is only a demo script which is not supposed to be used in production.

**Comment by peteringram0** [comment]
try changing 

"typescript": "^1.9.0-dev.20160625-1.0"

TO

"typescript": "^1.8.10",
