### ISSUE TITLE
Unable to build/run project. Fails on es5

### ISSUE THREAD

**Issue by dmusicant** [mgechev/angular2-ngc-rollup-build#4]
I get the error:

npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "es5"  
npm ERR! node v4.3.1  
npm ERR! npm  v3.10.5  
npm ERR! code ELIFECYCLE  
npm ERR! angular2-min@1.0.0 es5: `tsc --target es5 --allowJs dist/bundle.es2015.js --out   dist/bundle.js`  
npm ERR! Exit status 2  

npm ERR! Tell the author that this fails on your system:  
npm ERR!     tsc --target es5 --allowJs dist/bundle.es2015.js --out dist/bundle.js

I cannot get it past this step. Even running it individually fails here.

**Comment by k3a** [comment]
Same as issue #2 (closed): "It is mentioned in the blog post. This is only a demo script which is not supposed to be used in production."

This doesn't seem to be a blocking problem though, the script is still transpired so you can make a hack and edit "es5" script to be this:

"es5": "tsc --target es5 --allowJs dist/bundle.es2015.js --out dist/bundle.js || true",

This will return success code to NPM even if tsc returns an error code.

There is a bigger problem with this method though #5. :(

**Comment by mgechev** [comment]
This is only a demo for the blog post, the repository is not intended to be used in production. A production ready starter can be found [here](https://github.com/mgechev/angular2-seed).
