### ISSUE TITLE
'ngc' is not recognized as an internal or external command

### ISSUE THREAD

**Issue by sanket360** [mgechev/angular2-ngc-rollup-build#6]
I took a copy of this repository and ran `npm run ngc` command.
For this, I am getting error-

> 'ngc' is not recognized as an internal or external command, operable program or batch file.

![ngc](https://cloud.githubusercontent.com/assets/16756121/17696945/68e309da-63cf-11e6-9983-e6347361a94d.PNG)

Do I need to set PATH? where exactly I need to point?

My environment is - 
OS Windows 7 64 bit
npm version 3.9.6
node version 4.4.7

**Comment by jgenchik** [comment]
I have the same problem. Did you find a solution?

**Comment by sanket360** [comment]
No... Not yet

**Comment by naveedahmed1** [comment]
Any updates?

**Comment by mgechev** [comment]
This is only demo coming with the blog post. The experiments I described are not meant for production usage. I'd suggest to use angular2-seed, angular-cli or any other starter which implements the described techniques. Since today angular2-seeds include AoT.

**Comment by mxlockwood** [comment]
mgechev: You didn't address the issue.

**Comment by gg-gg-v1** [comment]
@mxlockwood  @mgechev @naveedahmed1 @sanket360 @jgenchik
Did someone found the solution for this issue ?
I really need help..
- Thanks !
